### ISSUE TITLE
Add more detailed tutorial development guide

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/hackweeks-as-a-service#1]
expand on https://github.com/uwhackweek/hackweeks-as-a-service/blob/main/docs/tutorials.md and maybe take some screenshots that document how to make a new jupyter notebook for snowex hackweek. 

a short list of tutorial development resources:
- https://geohackweek.github.io/wiki/tutorial_leads.html 
- https://carpentries.github.io/instructor-training/ 
- https://carpentries.github.io/curriculum-development/ 
- framework for high-quality software documentation (tutorial, how-to, explanation, reference) https://diataxis.fr 

another thought is to use tutorial notebook 'templates' (https://github.com/earthcube/NotebookTemplates ). EarthCube is doing this for peer-reviewed notebooks that are being published here https://www.earthcube.org/notebooks

**Comment by aaarendt** [comment]
Thanks for prompting me to get this done @scottyhq! Feedback welcome on my new layout of those sections:

https://uwhackweek.github.io/hackweeks-as-a-service/tutorials.html

**Comment by scottyhq** [comment]
> Feedback welcome on my new layout of those sections

Nice! Looking great. We can incorporate the tutorial development guide as a page in this book eventually (it's just markdown),  I thought about that initially, but for simplicity and visibility just kept it under the snowex website.

> I feel like those EarthCube templates might be too heavy for what we're doing. Maybe we should create a general hackweek template though based on our past experience.

Agreed. Maybe just an empty notebook with markdown headings for suggested ordered sections such as:

1. learning objectives 
1. software libraries showcased
1. getting started (a quick win code example to get people interested)
1. exercise
1. more advanced concepts 
1. further reading / links to other resources
1. hackweek project ideas (mixed on this as we want participants to propose and lead projects)
