### ISSUE TITLE
create a "adding a hackweek to your proposal" guide

### ISSUE THREAD

**Issue by JessicaS11** [uwhackweek/hackweeks-as-a-service#16]
As discussed at our meeting, this would provide some tools and pointers to help proposal submitters who would like to include hackweek services in their budgets. Some ideas for what it might include:
 [ ] basic budget figures
 [ ] key first steps
 [ ] an overview for funders that proposers can cite to provide more information

**Comment by aaarendt** [comment]
Closing and making a note of these ideas in Notion, to be included in future work on the eScience website, where all content for new proposers now lives.
