### ISSUE TITLE
create badge-like text to complete #19

### ISSUE THREAD

**Issue by JessicaS11** [uwhackweek/hackweeks-as-a-service#20]
> In #15 we added some keyword "badges" to some of the detailed descriptions with keywords that help describe the professional development opportunities within the position. Currently each badge is created manually, but we'd like to use the Sphinx extension extlinks to clean up the syntax and make it easier. See [this comment](https://github.com/uwhackweek/hackweeks-as-a-service/pull/15#issuecomment-951354821) for more details on what still isn't working.

**Comment by aaarendt** [comment]
All this appears to be working on the new eScience interface. Propose closing this issue.

**Comment by aaarendt** [comment]
Closing since we're going to be using badger for issuing badges very soon and will replace our old approaches.
