### ISSUE TITLE
Change website url?

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/hackweeks-as-a-service#25]
We currently pay for the 'hackweek.io' domain name for a nominal annual fee. `https://uwhackweek.github.io/hackweeks-as-a-service` is a bit lengthy and cumbersome. So I suggest we change it either to:

1. https://uwhackweek.github.io
2. https://guidebook.hackweek.io

more details on options documented here:
https://github.com/uwhackweek/jupyterbook-template/issues/85

**Comment by scottyhq** [comment]
@aaarendt thoughts on changing the URL here to `https://guidebook.hackweek.io` ? I think it's much cleaner than `https://uwhackweek.github.io/hackweeks-as-a-service`. Note also that it is just a simple redirect, so the existing URL remains valid.

**Comment by aaarendt** [comment]
Yes, great idea @scottyhq. I think I favor uwhackweek.github.io however, just so it includes some reference to UW. But I see that it is more consistent across events if we go with hackweek.io for all websites. What do you think?

**Comment by scottyhq** [comment]
> I think I favor uwhackweek.github.io however, just so it includes some reference to UW. But I see that it is more consistent across events if we go with hackweek.io for all websites. What do you think? 

#4 has some suggestions around an organizational landing page (uwhackweek.github.io), so I'm in favor of this particular jupyterbook living at https://guidebook.hackweek.io. I'll add a PR

**Comment by aaarendt** [comment]
Yes, I see, that will be the book not the landing page. So this makes sense to me.
