### ISSUE TITLE
Update technology/recognition

### ISSUE THREAD

**Issue by jomey** [uwhackweek/hackweeks-as-a-service#51]
The logic to updating the team has changed with:
https://github.com/uwhackweek/jupyterbook-template/pull/157

**Comment by JessicaS11** [comment]
Started this work here: https://github.com/uwhackweek/hackweeks-as-a-service/tree/tech-module

**Comment by jomey** [comment]
> Started this work here: https://github.com/uwhackweek/hackweeks-as-a-service/tree/tech-module

Instead of copying the content - should we link to the `README` making it more proof to future changes?

**Comment by JessicaS11** [comment]
> should we link to the README making it more proof to future changes?

Absolutely - do we still want to have a series of images to go with the instructions? If so, will we add all of that to the readme?

**Comment by jomey** [comment]
> images to go with the instructions?

Are you thinking of the one image we had that shows how information will show up on a person card?

**Comment by JessicaS11** [comment]
> Are you thinking of the one image we had that shows how information will show up on a person card?

Based on the [original content](https://guidebook.hackweek.io/technology/recognition.html#uploading-to-the-website), we had step-by-step text-based instructions with images illustrating the process. I was figuring we'd be updating those to reflect the updated process (but that does potentially make it more cumbersome for a readme).

**Comment by jomey** [comment]
I think we can find a middle ground between the old and updating the new ReadMe to have some images with instructions.

**Comment by scottyhq** [comment]
closed by #62
