### ISSUE TITLE
Ensure code-of-conduct contact email is monitored

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/hackweeks-as-a-service#65]
https://github.com/uwhackweek/hackweeks-as-a-service/blob/178171dd16bb9b3d21d8a77ad986cdfce716cc34/CODE_OF_CONDUCT.md?plain=1#L61-L63

For Icesat-2 2023 we used `icesat2-hackweek@uw.edu` (https://icesat-2-2023.hackweek.io/CoC.html) 

Going over both this repository and our event jupyterbook templates I'd like to make sure the correct email contact is listed. I don't believe the old gmail account is still monitored, but not sure if there is a generic one across events we can use?

cc @aaarendt @markweldensmith

**Comment by spestana** [comment]
Would it be appropriate to also include contact information for the [UW Ombud](https://www.washington.edu/ombud/) office? I thought I'd seen that included in past event codes of conduct. The idea is to have another contact that is external to the hackweek organizers and eScience.

**Comment by scottyhq** [comment]
Yes, for clarity, we have two codes of conduct! 

1. The standard code of conduct GitHub recommends for all open repositories (so this repository and jupyterbook-template repository). The ombud shouldn't be on these I think. 

Here are two examples that go to a google group email address so that more than one person can be on it.
https://github.com/geopandas/geopandas/blob/main/CODE_OF_CONDUCT.md#reporting
https://github.com/pydata/xarray/blob/main/CODE_OF_CONDUCT.md#enforcement

1. The event-specific code of conduct that we share with all event participants. If you follow the 2023 icesat-2 event above this has 1. a custom email address, 2. a microsoft office anonymous form (that I assume goes to the custom email address, 3. ombud info

I think we want to switch both of these to `escience-hackweeks@uw.edu` for all events now but just want to make sure?

**Comment by aaarendt** [comment]
Thanks for working on this! Agreed we should use `escience-hackweek@uw.edu` as both Mark and I currently receive this directly in our inbox, and we can certainly add a few others of us before the event. (Mark knows a trick in gmail to have these go directly into a subfolder). 

Mark and I can work on updating the form. We can revert back to Google forms I think, or use Qualtrics. We'll share an updated link after that.

The 2023 icesat-2 CoC version matches what we've been using for at least the past 5 years. It includes Ombuds, Title IX and UCIRO as external-to-us entities. Happy to include any other updates but I think it is good to go. We should confirm all the links and phone numbers are currently up to date.

**Comment by aaarendt** [comment]
Changes are in https://github.com/uwhackweek/jupyterbook-template/pull/175
